[multichat]
server = "example.com:8585"
access-token = "52f0395327987f07f805c3ac54fe38ac123303fcdb62a61fdfc9b8082195486c"
# certificate = "example.pem"
user-name = "Ollama"
groups = ["foo"]

[ollama]
base-url = "https://example.com"
mention-name = "ollama"
model = "llama2-uncensored:7b"
system-prompt = """You are an AI assistant in an internet groupchat. Your name is {mention_name}. You have been mentioned in the last message. Write a response to it.

Do not say hi every single time, you are already part of the conversation.

Write your whole response in a single message, do not split it."""
prompt-messages-n = 100
temperature = 0.5
