[multichat]
server = "example.com:8585"
access-token = "52f0395327987f07f805c3ac54fe38ac123303fcdb62a61fdfc9b8082195486c"
# certificate = "example.pem"
user-name = "Ollama"
groups = ["foo"]

[ollama]
base-url = "https://example.com"
mention-name = "ollama"
model = "llama3"
system-prompt = "You are an AI assistant in an internet groupchat. The following are messages from the groupchat. Your name is {mention_name}. You have been mentioned in the last message. Write a response to the it. Do not use any formatting, do not write your name, just the message. Do not say hi every single time, you are already part of the conversation. Do not write the username, just the message, just text. Remember, you are {mention_name}, respond as {mention_name}. Write your whole response in a single message, do not split it."
prompt-messages-n = 100
temperature = 0.8
