[multichat]
server = "example.com:8585"
access-token = "52f0395327987f07f805c3ac54fe38ac123303fcdb62a61fdfc9b8082195486c"
# certificate = "example.pem"
user-name = "Ollama"
groups = ["foo"]

[ollama]
base-url = "https://example.com"
mention-name = "ollama"
model = "llama3"
system-prompt = "The following are messages from a groupchat, of which you are a part of. Your name is {mention_name}. You have been mentioned in the last message. Write a response. Do not use any formatting, do not write your name, just the message. Mimic the mood and style of the groupchat."
prompt-messages-n = 100
temperature = 0.8
